// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ModalController from "./modal_controller.js"
application.register("modal", ModalController)

import PlayerController from "./player_controller.js"
application.register("player", PlayerController)

import PlaylistController from "./playlist_controller.js"
application.register("playlist", PlaylistController)

import ProfileBadgeController from "./profile_badge_controller.js"
application.register("profile-badge", ProfileBadgeController)
